imports:
  - { resource: src/Captcha/services.yaml }
  - { resource: src/PasswordPolicy/services.yaml }

services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\SecurityModule\Core\Registry:
    class: 'OxidEsales\Eshop\Core\Registry'
    public: true
