imports:
  - { resource: src/PasswordPolicy/services.yaml }

services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\SecurityModule\PasswordPolicy\Service\ModuleSettingInterface:
    class: OxidEsales\SecurityModule\PasswordPolicy\Service\ModuleSetting
    public: true
