services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Request: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getRequest()'
      OxidEsales\Eshop\Core\Utils: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getUtils()'

  OxidEsales\SecurityModule\PasswordPolicy\Service\ModuleSettingsServiceInterface:
    class: OxidEsales\SecurityModule\PasswordPolicy\Service\ModuleSettingsService
    public: true

  OxidEsales\SecurityModule\PasswordPolicy\Validation\Validator\MinimumLengthValidator:
    tags: [ 'security.password.validator' ]

  OxidEsales\SecurityModule\PasswordPolicy\Validation\Validator\SpecialCharValidator:
    tags: [ 'security.password.validator' ]

  OxidEsales\SecurityModule\PasswordPolicy\Validation\Validator\DigitValidator:
    tags: [ 'security.password.validator' ]

  OxidEsales\SecurityModule\PasswordPolicy\Validation\Validator\UpperCaseValidator:
    tags: [ 'security.password.validator' ]

  OxidEsales\SecurityModule\PasswordPolicy\Validation\Validator\LowerCaseValidator:
    tags: [ 'security.password.validator' ]

  OxidEsales\SecurityModule\PasswordPolicy\Intrastructure\ExceptionFactoryInterface:
    class: OxidEsales\SecurityModule\PasswordPolicy\Intrastructure\ExceptionFactory
    public: true

  OxidEsales\SecurityModule\PasswordPolicy\Validation\Service\PasswordValidatorChainInterface:
    class: OxidEsales\SecurityModule\PasswordPolicy\Validation\Service\PasswordValidatorChain
    public: true
    arguments:
      $validators: !tagged 'security.password.validator'

  OxidEsales\SecurityModule\PasswordPolicy\Validation\Service\PasswordStrengthServiceInterface:
    class: OxidEsales\SecurityModule\PasswordPolicy\Validation\Service\PasswordStrengthService
    public: true

  OxidEsales\SecurityModule\PasswordPolicy\Validation\Service\StringAnalysisServiceInterface:
    class: OxidEsales\SecurityModule\PasswordPolicy\Validation\Service\StringAnalysisService

  OxidEsales\SecurityModule\PasswordPolicy\Transput\RequestInterface:
    class: OxidEsales\SecurityModule\PasswordPolicy\Transput\Request
    public: true

  OxidEsales\SecurityModule\PasswordPolicy\Transput\ResponseInterface:
    class: OxidEsales\SecurityModule\PasswordPolicy\Transput\Response
    public: true

  OxidEsales\SecurityModule\PasswordPolicy\Validation\Service\CharacterAnalysisServiceInterface:
    class: OxidEsales\SecurityModule\PasswordPolicy\Validation\Service\CharacterAnalysisService
