imports:
  - { resource: Infrastructure/services.yaml }
  - { resource: Service/services.yaml }
  - { resource: Transput/services.yaml }
  - { resource: Controller/services.yaml }
  - { resource: Factory/services.yaml }
  - { resource: OTP/services.yaml }
