install_shop_with_modules:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/oxideshop-pe": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/oxideshop-ee": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component-pe": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component-ee": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/developer-tools": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/security-module": "dev-{{ .Github.RefName }}"
          },
          "repositories": {
            "oxid-esales/security-module": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/security-module.git"
            },
            "oxid-esales/oxideshop-ee": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/oxideshop_ee.git"
            },
            "oxid-esales/oxideshop-pe": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/oxideshop_pe.git"
            },
            "oxid-esales/twig-component-pe": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/twig-component-pe.git"
            },
            "oxid-esales/twig-component-ee": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/twig-component-ee.git"
            }
          }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:database:reset --db-host=mysql --db-port=3306 --db-name=example --db-user=root --db-password=root --force
    vendor/bin/oe-console oe:module:activate oe_security_module
    vendor/bin/oe-console oe:theme:activate apex

runscript: &runscript
  matrix:
    script: |
      [
        "security_module:tests-unit",
        "security_module:tests-integration",
        "security_module:tests-codeception"
      ]
  composer:
    early: true
  security_module:
    path: 'vendor/oxid-esales/security-module'

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "security_module:phpcs",
        "security_module:phpstan",
        "security_module:phpmd"
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/vendor/oxid-esales/security-module/'
  project_key: 'OXID-eSales_security-module'
  project_name: 'oxid-esales/security-module'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests
    -Dsonar.php.phpstan.reportPaths=coverage-reports/phpstan.report.json

finish:
  slack_title: 'Security module ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
