services:
  _defaults:
    autowire: true
    public: false
    bind:
      OxidEsales\Eshop\Core\Request: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getRequest()'

  OxidEsales\SecurityModule\Authentication\OAuth2\Transput\OAuthRequestInterface:
    class: OxidEsales\SecurityModule\Authentication\OAuth2\Transput\OAuthRequest
    public: true
