services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\SecurityModule\Authentication\OAuth2\Service\Provider\Facebook\Facebook:
    tags: [ 'security.oauth.tag.provider' ]

  OxidEsales\SecurityModule\Authentication\OAuth2\Service\Provider\Google\Google:
    tags: [ 'security.oauth.tag.provider' ]
