services:
  _defaults:
    autowire: true
    public: false
    bind:
      OxidEsales\Eshop\Core\UtilsView: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getUtilsView()'

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Controller\TwoFactorAuthController:
    public: true
    tags:
        - { name: 'oxid.view_controller', controller_key: 'twofactorauth' }
