services:
  _defaults:
    autowire: true
    public: false
    bind:
      OxidEsales\Eshop\Core\Config: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getConfig()'

  OxidEsales\SecurityModule\Authentication\OAuth2\Service\ModuleSettingsServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\OAuth2\Service\ModuleSettingsService
    public: true

  OxidEsales\SecurityModule\Authentication\OAuth2\Service\UserServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\OAuth2\Service\UserService
    public: true

  OxidEsales\SecurityModule\Authentication\OAuth2\Service\ProviderCollectorInterface:
    class: OxidEsales\SecurityModule\Authentication\OAuth2\Service\ProviderCollector
    public: true
    arguments:
      $providers: !tagged 'security.oauth.tag.provider'

  OxidEsales\SecurityModule\Authentication\OAuth2\Service\AuthenticationServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\OAuth2\Service\AuthenticationService
    public: true

