imports:
  - { resource: Factory/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Infrastructure\Provider\EmailAdapter:
    tags: [ 'security.twofa.tag.notify.provider' ]
