services:
  _defaults:
    autowire: true
    public: false
    bind:
      OxidEsales\Eshop\Core\Utils: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getUtils()'

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Transput\AuthCodeRequestInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Transput\AuthCodeRequest
    public: true

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Transput\JsonResponseInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Transput\JsonResponse
    public: true

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Transput\UserSettingsUpdateRequestInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Transput\UserSettingsUpdateRequest
    public: true
