imports:
  - { resource: Infrastructure/Repository/services.yaml }
  - { resource: Service/services.yaml }
  - { resource: Notifier/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\OTP\OtpFacade: ~
