services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Factory\TwoFAServiceFactoryInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Factory\TwoFAServiceFactory
    arguments:
      $implementations:
        otp: '@OxidEsales\SecurityModule\Authentication\TwoFactorAuth\OTP\OtpFacade'

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\TwoFAServiceInterface:
    factory: ['@OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Factory\TwoFAServiceFactoryInterface', 'create']
    public: true
