services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\SecurityModule\Captcha\Service\CaptchaServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Service\CaptchaService
    public: true
