services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Utils: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getUtils()'
      OxidEsales\Eshop\Core\Request: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getRequest()'
      OxidEsales\Eshop\Core\Session: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getSession()'

  OxidEsales\SecurityModule\Captcha\Service\ModuleSettingsServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Service\ModuleSettingsService
    public: true

  OxidEsales\SecurityModule\Captcha\Captcha\Image\Service\ImageCaptchaServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Captcha\Image\Service\ImageCaptchaService

  OxidEsales\SecurityModule\Captcha\Service\CaptchaAudioServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Service\CaptchaAudioService
    public: true

  OxidEsales\SecurityModule\Captcha\Captcha\HoneyPot\Service\HoneyPotCaptchaServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Captcha\HoneyPot\Service\HoneyPotCaptchaService

  OxidEsales\SecurityModule\Captcha\Service\CaptchaServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Service\CaptchaService
    public: true
    arguments:
      - '@OxidEsales\SecurityModule\Captcha\Captcha\Image\Service\ImageCaptchaServiceInterface'
      - '@OxidEsales\SecurityModule\Captcha\Captcha\HoneyPot\Service\HoneyPotCaptchaServiceInterface'

  OxidEsales\SecurityModule\Captcha\Captcha\Image\Builder\ImageCaptchaBuilderInterface:
    class: OxidEsales\SecurityModule\Captcha\Captcha\Image\Builder\ImageCaptchaBuilder

  OxidEsales\SecurityModule\Captcha\Transput\ResponseInterface:
    class: OxidEsales\SecurityModule\Captcha\Transput\Response
    public: true

  OxidEsales\SecurityModule\Captcha\Captcha\Image\Validator\ImageCaptchaValidatorInterface:
    class: OxidEsales\SecurityModule\Captcha\Captcha\Image\Validator\ImageCaptchaValidator

  OxidEsales\SecurityModule\Captcha\Form\ContactFormCaptchaValidator:
    class: OxidEsales\SecurityModule\Captcha\Form\ContactFormCaptchaValidator

  OxidEsales\SecurityModule\Captcha\Form\ContactFormDecorator:
    decorates: OxidEsales\EshopCommunity\Internal\Domain\Contact\Form\ContactFormBridgeInterface
    decoration_on_invalid: ignore
    arguments:
      - '@.inner'
      - '@OxidEsales\SecurityModule\Captcha\Form\ContactFormCaptchaValidator'
