services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Utils: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getUtils()'
      OxidEsales\Eshop\Core\Request: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getRequest()'
      OxidEsales\Eshop\Core\Session: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getSession()'
      OxidEsales\Eshop\Core\Language: '@=service("OxidEsales\\SecurityModule\\Core\\Registry").getLang()'

  OxidEsales\SecurityModule\Captcha\Infrastructure\LanguageWrapperInterface:
    class: OxidEsales\SecurityModule\Captcha\Infrastructure\LanguageWrapper

  OxidEsales\SecurityModule\Captcha\Service\ModuleSettingsServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Service\ModuleSettingsService
    public: true

  OxidEsales\SecurityModule\Captcha\Captcha\Image\Service\ImageCaptchaServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Captcha\Image\Service\ImageCaptchaService
    tags: [ 'security.captcha' ]

  OxidEsales\SecurityModule\Captcha\Captcha\Image\Service\CaptchaAudioServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Captcha\Image\Service\CaptchaAudioService
    public: true

  OxidEsales\SecurityModule\Captcha\Captcha\HoneyPot\Service\HoneyPotCaptchaServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Captcha\HoneyPot\Service\HoneyPotCaptchaService
    tags: [ 'security.captcha' ]



  OxidEsales\SecurityModule\Captcha\Service\CaptchaServiceInterface:
    class: OxidEsales\SecurityModule\Captcha\Service\CaptchaService
    public: true
    arguments:
      $captchas: !tagged 'security.captcha'

  OxidEsales\SecurityModule\Captcha\Captcha\Image\Builder\ImageCaptchaBuilderInterface:
    class: OxidEsales\SecurityModule\Captcha\Captcha\Image\Builder\ImageCaptchaBuilder

  OxidEsales\SecurityModule\Captcha\Transput\ResponseInterface:
    class: OxidEsales\SecurityModule\Captcha\Transput\Response
    public: true

  OxidEsales\SecurityModule\Captcha\Captcha\Image\Validator\ImageCaptchaValidatorInterface:
    class: OxidEsales\SecurityModule\Captcha\Captcha\Image\Validator\ImageCaptchaValidator

  OxidEsales\SecurityModule\Captcha\Form\ContactFormCaptchaValidatorInterface:
    class: OxidEsales\SecurityModule\Captcha\Form\ContactFormCaptchaValidator

  OxidEsales\SecurityModule\Captcha\Form\ContactFormDecorator:
    decorates: OxidEsales\EshopCommunity\Internal\Domain\Contact\Form\ContactFormBridgeInterface
    decoration_on_invalid: ignore
    arguments:
      - '@.inner'
      - '@OxidEsales\SecurityModule\Captcha\Form\ContactFormCaptchaValidatorInterface'
