imports:
  - { resource: Provider/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\ModuleSettingsServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\ModuleSettingsService

  OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\AuthorizeServiceInterface:
    class: OxidEsales\SecurityModule\Authentication\TwoFactorAuth\Service\AuthorizeService
