services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\SecurityModule\Authentication\OAuth2\Infrastructure\Repository\UserRepositoryInterface:
    class: OxidEsales\SecurityModule\Authentication\OAuth2\Infrastructure\Repository\UserRepository
